{{- if and .Values.tls.enabled .Values.tls.serviceAccount.create }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ template "cockroachdb.tls.serviceAccount.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  {{- with .Values.tls.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    helm.sh/chart: {{ template "cockroachdb.chart" . }}
    app.kubernetes.io/name: {{ template "cockroachdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
